### PR TITLE
chore(charts/paperless-ngx): remove line breaks from comments

### PR DESCRIPTION
**Pull request by fty4**
#### What this PR does / why we need it

Just removes some whitespace / line breaks which will be generated from comments in [`charts/paperless-ngx/templates/configmap.yaml`](https://github.com/fmjstudios/helm/blob/fea914b264718488c3104292280c9d705bf1c3a1/charts/paperless-ngx/templates/configmap.yaml#L363).
Also updating helpers for same comment convention.

#### Which issue this PR fixes

no issue created

#### Special notes for your reviewer

no special note

#### Checklist

- [ ] Chart Version bumped **-> waiting for other open PR #20 before bumping version**
- [x] User name added to [`AUTHORS`](AUTHORS) **-> file added via other PR**
- [x] Title of the PR starts with a valid commit scope as detailed in the [CONTRIBUTING](../docs/CONTRIBUTING.md) (e.g.
      `fix(charts/linkwarden): ...`)

### CODE REVIEW

**Comment by fty4** [comment]
Please do not close PR - still valid.

**Comment by fty4** [comment]
Hello @FMJdev I've bumped the chart version - after this is merged I also will bump the version of #22 if this is fine for you!

I added some fix to complete ct lint (new linke, spaces) - but still struggling with the following:

```
 ✖︎ paperless-ngx => (version: "0.2.5", path: "charts/paperless-ngx") > failed validating maintainer "FMJ Studios Helm Authors": 404 Not Found
``` 

How would you link to fix that?
If you want I can move the fix commits into another PR (I added theme here to get sucessful checks).

**Comment by fty4** [comment]
It seems the name must match a GitHub username / organization.

```diff
diff --git a/charts/paperless-ngx/Chart.yaml b/charts/paperless-ngx/Chart.yaml
index cbc6df7..4123eed 100644
--- a/charts/paperless-ngx/Chart.yaml
+++ b/charts/paperless-ngx/Chart.yaml
@@ -36,7 +36,7 @@ keywords:
 sources:
   - "https://github.com/fmjstudios/helm"
 maintainers:
-  - name: FMJ Studios Helm Authors
+  - name: fmjstudios
     email: info@fmj.studio
   - name: FMJdev
     email: info@fmj.dev
```

When adding this change the linting will be sucessful.

see: helm/chart-testing#659

**Comment by FMJdev** [comment]
Hey, first off thank you for the research into the issue. Very surprising to see this pop up now. I wanted to use the Authors rather than the GitHub Org to credit everybody in the `AUTHORS` file, but nvm I guess.

I took a closer look at the issue and like you noted and commited `ct` will then start complaining about bracket spacing and missing ending newlines. I wanted to add `pre-commit` anyways to aid with consistency and took the time to erase all of these issues across all charts as well as add a new `chart-testing` target for `make` for more regular linting. Sorry for voiding your work somewhat there. I published `0.2.5` already as a result of this so I'd kindly ask you to edit the PR a final time 🤞🏼 

Feel free to edit #22 once we have this sorted out. I'll merge when you've had the time. Thanks a lot once again! 🥇

**Comment by fty4** [comment]
Solved the merge conflict and bumped the chart version.

Now creating the kind cluster in [`Testing`](https://github.com/fmjstudios/helm/actions/runs/11832512221/job/32969498863?pr=21#step:7:40) failed:

> docker: Error response from daemon: driver failed programming external connectivity on endpoint chart-testing-control-plane (00b7cdf4af30278583d36d498b18c9c4576dc29d2a88e921150f312a1e88bfd3): Error starting userland proxy: listen tcp4 0.0.0.0:22: bind: address already in use.

**Comment by FMJdev** [comment]
How fitting for all of this to pop up during your PR, not during my hundreds of commits 😆 The `Testing` workflow is quite finicky due to the _changed_ checks 👈🏼  I'm going to forego CI here since it's a bogus issue and I'm going to take a closer look at it on the weekend. Seems like GitHub's CI machines already have port 22 bound, obviously most likely for SSH but I would've expected CI runners to use custom ports. 

Nonetheless, thank you for all your work so far! 🥇

**Pull request merged**
